### PR TITLE
Provide default Assistify-specific configuration of Rocket.Chat

### PR DESCRIPTION
**Pull request by mrsimpson**
This PR brings a set of settings and roles as required by assistify @ DB.
This PR includes the settings-based-permissions as they are kind-of a pre-requisite. Only the package `assistify-configuration` is added on top of it.

### CODE REVIEW

**Comment by vickyokrm** [comment]
Roles are not created as expected after starting the application with the command ```meteor reset && meteor npm i && meteor```
P.S: MongoDB was cleared completely before starting the application

**Comment by vickyokrm** [comment]
The Assistify:configuration package is added to project.

**Comment by ruKurz** [comment]
The test cases fail:
```[Rocket.Chat Settings based permissions]
    Give User Permissions
      1) "before all" hook
      2) "after all" hook


  573 passing (2m)
  191 pending
  2 failing

  1) [Rocket.Chat Settings based permissions]
       Give User Permissions
         "before all" hook:
     Uncaught Error: unknown error: Cannot read property 'username' of null
      at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
      at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
      at Request.self.callback (node_modules/webdriverio/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/webdriverio/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  2) [Rocket.Chat Settings based permissions]
       Give User Permissions
         "after all" hook:
     Uncaught Error: element (".sidebar-flex__close-button[data-action="close"]") still not visible after 5000ms
      at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:150:12)
      at node_modules/webdriverio/build/lib/commands/waitUntil.js:29:19
      at node_modules/meteor-promise/fiber_pool.js:43:40```

**Comment by ruKurz** [comment]
I think there have been changes in parallel:
https://github.com/assistify/Rocket.Chat/pull/430/commits/a4768c128902a0c20e336add28f7dad741ede72e

**Pull request merged**
