### PR TITLE
Release 0.59.2-0.4.2 - massive refactoring, new RC base version, all new and almost shiny

### PR DESCRIPTION
**Pull request by mrsimpson**
# Purpose
This PR contains the basis of Assistify Rocket.Chat the way it should have been from the beginning: Loose coupling towards RC, less legacy artifacts, better quality (though still far from perfect).
In order to do that, RC needed to be updated to the most recent version.

# Diff towards `develop`
Sinve the changelist is huge, the following list describes what's been done in order to achive the current state

- Update RC to the upcoming versoin 0.59.0 (currently release candidate 15, b9585e0c8657817cb6e1719c9972c1d6da9bd9c5)
- Merge the new room types API as per RocketChat#8264 (cf4c44133d64c1801e538ae5476936667a891a99) -> to be included in RC 0.60
- Merge a room type creation UI as per RocketChat#8264 (e23699fbc587a8a732c6a37957b9fc6935396adc) -> PR to be created once the earlier one is merged
- Remove a lot of unnecessary files from Smarti's ancestors (Reisebuddy and Hasso) => get rid of almost all Blaze-templates, since Smarti brings its own UI
- Remove the common super-package in order to make the two main packages isolated from each other
- Many small fixes
- Better documentation

# Call to action
Due to the massive changelist, I ask all fellow developers to 

- check out this branch
- perform manual testing (writing automated tests is of course more than appreciated ;)
- Have a look at the folder and file structure, check dependencies - it should be verbose to anybody doing that what the purpose and general functionality is
- comment on the PR by adding a review

@janrudolph I'll publish this release-candiadate to our team-server soon and ask you for functional testing.

### CODE REVIEW

**Comment by mrsimpson** [comment]
Changed the title of the PR as 0.59.1 is already in the wild. Minor changes have been performed. Thus, 0.59.1-0.4.1 is the content to be merged (though the name of the source branch is different). 
This version has been deployed to the team-chat 
=> @janrudolph you can perform integration testing

**Comment by janrudolph** [comment]
@mrsimpson First thing which I noticed: No bold channel names when a new messages was posted into channel. That is very confusing.

**Comment by mrsimpson** [comment]
@janrudolph merged the latest fix version of RC. This should have fixed the guest pool. Can you please test and confirm?

**Comment by janrudolph** [comment]
The following things were tested successfully:

- Creation & closing of requests 
- Creation of topics
- Suggestions by Smarti are displayed
- Sharing Smarti results is possible
- Basic Livechat operations (taking messages, answering)
- Smarti suggestions are in livechat present

The following tests have failed:

- Scrolling in the right sidebar ist not possible
- Smarti (Sidebar) is not open by default in request rooms
- Deletion of channels (public, private, topics) is not possible (within a channel using the sidebar options; even as admin)

**Comment by mrsimpson** [comment]
@janrudolph the issues found shall be fixed. Couldn't test the Smarti scrolling due to missing test-data / connectivity. If that's fine, please accept the review

**Comment by mrsimpson** [comment]
I didn't get the scrollbar hidden properly ;( Now, once again two hierarchical scrollbars are there. Let's leave it for now, this is not crucial.
As all the rest has been validated, I'm merging this to develop now.

**Pull request merged**
