### PR TITLE
Feature/#145 ask question from room

### LINKED ISSUE #145: Make people ask questions - heavyweight threading from every room
## Motivation

We want to make people ask questions in an isolated room - since only this makes knowledge re-useable.

## Current situation
Currently, Assistify only offers one way of asking a question: creating a request via the create-room-dialog. This does not only have a second-class user experience, it also relies on the user knowing (and appreciating) the different room types.
Sometime, a user recognizes that he's got a question which could and should be processed in an isolated way - but the barrier of leaving the channel and creating a request for a topic which may not even exist is too high.

## Proposal
As user I want to create a new request based on a chat-message

bildschirmfoto_2017-11-10_um_12_28_39

By click on "Get help" the question shall be extracted to a new room. In the original room, a link to the newly created one shall be placed so that others can follow-up.
All members of the room from where it's been branched-off shall be integrated into the new room.

## Dependencies
- Belongs to #177 
- Is affiliated with #178 
- Requires Smarti to integrated knowledge not with fixed filters based on expertises - the segment of knowledge which can be used for solving this question has to be determined differently

### PR DESCRIPTION
**Pull request by vickyokrm**
closes  #145  [Enable users to ask questions from an existing chat room]

**Reference to previous pull request closed due to inconsistency in the issue with branch name #232** 

**Feature Overview:**
To allow users to ask help about a conversation while they are in a chat room.

**Motivation:**
This feature will enable user to ask more questions in an isolated way which implies the new help request is created in the current conversation context.

**Benefits of the solution:**

- Enable users to pro-actively communicate with out being afraid of leaving the chat room in which the user is conversing.

- Using Assistify as a platform to ask and communicate more intensive.

**What has changed/introduced:**

1. A new Message Action so called 'Help' has been introduced shall be used to create help request for a particular message.

1. The new help request creation feature will prompt user to provide a request title a optional field.

1. Upon confirmation, a new help request room will be created propagating the experts users and the question/query to the new room.

**What is missing:**

- [x] Translation of the texts in Deutsch

- [x] Code review from reviewer

- [x] Feedback

### CODE REVIEW

**Comment by ThomasRoehl** [comment]
All tests run through!
I still see 2 minor problems:
- When using the `ask question` feature, the dialog field says: `the topic for the new request`, this might be confusing, since the word `topic` is internally used for expertises but in this case, it means title or name.
- When using a title that already exists, no feedback is given, the create button still works, but no request is created and you don't switch to the existing request.

**Comment by ThomasRoehl** [comment]
Tests have to be fixed. It still assumes to have the dialog window

**Comment by mrsimpson** [comment]
image

**Comment by janrudolph** [comment]
Review results:

- Original message will be replaced by bot message.
- Look and feel of the bot message in the original channel see above (mrsimpson's comment)
- The user, which posts the bot message, looks like the user who has posted the question OR the assistify user will do so 
- In the sub-channel, first a bot message indicates, that the new channel is a sub channel of XY and asks the user to help the questioner. Additionally, the bot will ask the users to close the channel once the question has been answered. 
- The original question is posted as second message by the user who asked the question in the parent channel.

**Comment by mrsimpson** [comment]
Current state of threading (click, it's a video ;) ):
[Click to preview](https://github.com/assistify/assistify.github.io/blob/master/videos/Threading.mp4)

**Pull request merged**
