### PR TITLE
[NEW] config experts can manage apps

### PR DESCRIPTION
**Pull request by jschirrmacher**
I added the permission for `config-experts` to manage apps.

### CODE REVIEW

**Comment by jschirrmacher** [comment]
When someone with `manage-apps` permission calls the marketplace, the following message appear:
Bildschirmfoto 2019-11-19 um 14 43 02
If they try to install an app, the same message is shown.
It is still possible to enable / disable already installed apps.
I tried that in our `open` workspace.

Though I don't know, which permission is necessary to use the marketplace, I don't see a problem here regarding giving `manage-apps` to `config-manager` role.

**Comment by jschirrmacher** [comment]
Current status:
We checked that giving the permission `manage-apps` to `config-experts` doesn't allow them to connect the Marketplace with the Cloud, nor to install new apps, but only to enable/disable/configure apps which are already installed.

@mrsimpson will talk to RC people though, if this is the desired behavior or a bug.

**Comment by ruKurz** [comment]
> @mrsimpson will talk to RC people though, if this is the desired behavior or a bug.
From the permission perspective, I would say it's correct. But from the UI perspective, I would say it's a usability bug. Since only experts are effected (which are hopefully fault tolerant), this is not that critical. We should report it to Rocket.Chat anyways.

**Comment by jschirrmacher** [comment]
So you think, we should merge this PR? @ruKurz

**Pull request merged**
