### PR TITLE
Merge Rocket.Chat 0.73

### PR DESCRIPTION
**Pull request by mrsimpson**
This was a major release with a lot of merge conflicts.
Majorly, auto translation, threading and setting based permissions were giving conflicts.
=> Some manual testing is definitely required

### CODE REVIEW

**Comment by vickyokrm** [comment]
- DEEPL translation is intact.
- BUHU translation is working as expected.

**Comment by mrsimpson** [comment]
Have you verified livechat?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vickyokrm** [comment]
Live chat tests are successful.

**Comment by vickyokrm** [comment]
Threading- no change, working as expected.

**Comment by vickyokrm** [comment]
All sets are thru!

**Pull request merged**
