### PR TITLE
Create configuration expert role on startup

### PR DESCRIPTION
**Pull request by mrsimpson**
This PR add a role "config expert" (Fachadmin) which has a set of uncritical permissions.
Since those permissions include setting-based-permissions, this PR is based upon the setting-based-permissions.

Once this is merged into `develop`, this branch can be merged as well.

### CODE REVIEW

**Comment by mrsimpson** [comment]
@reviewers: What to test: 

- The role should be created automatically
- The role's permission should match our needs
- Users with this role should be allowed to change uncritical settings
- Code should be understandable

**Comment by ThomasRoehl** [comment]
I started reviewing on that

**Comment by ThomasRoehl** [comment]
Test results:
The config-expert role is create automatically.
All settings are set correctly.
The following administration settings are visible for config-expert:

> 
> Info
> Rooms
> Users
> Custom Emoji
> Integrations
> 
> Accounts
> Assets
> Email
> General
> Internal Hubot
> Layout
> Livechat
> Message

Possible Issues:
Config-expert can remove the admin role from the admin user but not it back.
Config-expert can deactivate the admin user.
default language was set to Chinese or something like that

**Comment by mrsimpson** [comment]
I have to admit that naming the role `config-expert` with "uncritical" permissions and mapping it to our "Fachadmin" was a bad naming idea.

Thus, I effectively renamed it to "minor-admin"

**Pull request merged**
