### PR TITLE
Release 0.65.2-0.8.2

### PR DESCRIPTION
**Pull request by mrsimpson**
This release brings a newer base version of Rocket.Chat.
Also, it enabled Chatpal.Search with a non-Smarti-provider (external Solr)

### CODE REVIEW

**Comment by mrsimpson** [comment]
Continuous delivery via `tar.gz` to our Opsworks-Stack was successful => servers started.
Continuous delivery via docker failed due to missing dependency

**Comment by mrsimpson** [comment]
@ruKurz I reverted the merge of the translation feature which braucht the "cld-on-docker" issue.
Feel free to merge this once

- the tests have completed
- you could upgrade our team chat to the `assistify/chat:pr-426` image

**Comment by ruKurz** [comment]
Our Team Chat is now running on `assistify/chat:pr-426` and looks good.
Is there anything left keeping us away to merge / release this PR?

**Comment by mrsimpson** [comment]
No. Ship it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
