### PR TITLE
Add thread creation

### PR DESCRIPTION
**Pull request by mrsimpson**
This is a real early WIP. The purpose of this PR is to discuss which features are going to be copied from the previous implementation based on requests.

Addresses #418

### CODE REVIEW

**Comment by mrsimpson** [comment]
@vickyokrm how far is this completed?

**Comment by mrsimpson** [comment]
There have been some bugs in the core which prevented proper linking of the messages. I opened aPR: https://github.com/RocketChat/Rocket.Chat/pull/11745

**Comment by mrsimpson** [comment]
- [X] The issues from Migration / configuration have been completed (except the weird settings behaviour, which seems to be an issue from the underlying RC). 
- [X] The "dialog must"s have been corrected.

=> In my opinion, the rest is optional. Testing the migration on our team chat, I noticed that the threads on the very top can be really disturbing: If there are many threads open, the unread and favorite rooms are dropping out of sight => I moved the threads list behind those two sections:
image

**Comment by ThomasRoehl** [comment]
We should definitely rename the entry points for the threading to something less technical like:
"Ask a question" or "Discuss about this".
I don't think many people know the meaning of threading and from a UI perspective, it doesn't look a lot like a thread, more like a separate room with a link to another room. Therefore I wouldn't call it threading to not distract the users

**Comment by mrsimpson** [comment]
@ThomasRoehl agreed. But we should do this using custom translations which we configure. With respect to including it into the standard, "thread" seems to be the term to be used. In addition, a hierarchical visualization will be added later.

**Comment by mrsimpson** [comment]
@ruKurz As agreed, we should check the usage of topics and communicate the change to publicly available rooms.
If we cannot do that for whatever reason, see https://github.com/assistify/Rocket.Chat/commit/b73a2c711a0372d442ad9eddd889a77ee58b9958:
This alternative migration will create a public (empty) room with the same name and add rename the old topic to `*-intern`.

**Pull request merged**
