### PR TITLE
#116 close request

### LINKED ISSUE #116: Message that indicates a closed request room
When closing a request room, the experts are removed and the "Chat beenden" button disappears. Just the creator of the request room stays in the room. If an expert has closed the room, the creator is not notified by this event. Thereby it is possible, that the creator does not have a clue, that all experts had left the channel. 

Therefore we need any form of notification, that the channel is now closed. Possible solutions might be:
- Write a message in the channel "channel closed"
- Replace the "Chat beenden" by a message "channel closed"

### LINKED ISSUE #120: Closing a request: Users kicked
# Motivation

When closing a request, all users are currently removed from the room. Thus, they cannot access the room anymore. This is unpleasant and an issue when it comes to performing search lateron.

# Expected behaviour

The users' subscriptions shall be removed so that they can still access the room, but they don't have it in the navigation bar.

### PR DESCRIPTION
**Pull request by mrsimpson**
Closing a request adds the comment properly and creates an automated message explaining what that means - fixes #116 

anfrage schliessen

### CODE REVIEW

**Comment by mrsimpson** [comment]
During this course, also added proper warnings for hiding and leaving:

Hide request
hide request

Leave request
leave request

Hide topic
hide expert

Leave topic
leave expert

**Comment by ruKurz** [comment]
- On local dev env I do not see the localized messages (only the keys / see attached snapshot)
- I get some JavaScript errors in the browser's log (in isLivechat, isOpenLivechat / see below)
- From the functional perspective it seems to work properly

bildschirmfoto 2017-11-01 um 21 46 38

```
Exception in template helper: TypeError: Cannot read property 't' of undefined
    at Object.**isLivechat** (http://localhost:3000/packages/assistify_ai.js?hash=bb18f0e62ece6ce59bd4e92fd7e3c040042666a7:230:5)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at http://localhost:3000/packages/assistify_ai.js?hash=bb18f0e62ece6ce59bd4e92fd7e3c040042666a7:121:22
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2734:44)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20
meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:942 Exception in template helper: TypeError: Cannot read property 't' of undefined
    at **Object.isOpenLivechat** (http://localhost:3000/packages/assistify_help-request.js?hash=39a3ba00d1f1ba673ea9b31bc58071bb9a128e36:1088:15)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at Template.HelpRequestActions.Blaze.If.HTML.DIV.class (http://localhost:3000/packages/assistify_help-request.js?hash=39a3ba00d1f1ba673ea9b31bc58071bb9a128e36:1014:22)
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2734:44)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20`
``

**Comment by mrsimpson** [comment]
The texts missing might be a problem of some Meteor cache. Please run `meteor reset` prior to `meteor npm start`.
As per the client exceptions: I believe this is not a problem of this change, but we should have a look at it. It might be a follow-up-problem of another issue

**Comment by mrsimpson** [comment]
merged with f18a657e3ae98135179b12753e8fbd689d733511

**Pull request merged**
