### PR TITLE
Merge Rocket.Chat 1.1

### PR DESCRIPTION
**Pull request by mrsimpson**
This PR brings the very latest Rocket.Chat [1.1.3](https://github.com/RocketChat/Rocket.Chat/releases/tag/1.1.3).
The change list from [1.1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/1.1.0) implies it's majorly a bugfix release.

### CODE REVIEW

**Comment by vickyokrm** [comment]
Unit tests are successfully gone thru.

**Comment by mrsimpson** [comment]
What about Smarti? I can see some strange effect here. 

@vickyokrm what about the grey-to-black logic? Is the status also in this release only updated after all other subscriptions have been updated?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vickyokrm** [comment]
grey-to-black: With DDP limiter, the issue was not locally reproducible as the limiter controls the requests in a given time interval. Without DDP limiter, the issue doesn't surface locally.

**Comment by vickyokrm** [comment]
@mrsimpson Which status you refer to?

**Comment by mrsimpson** [comment]
@vickyokrm I fixed Smarti and the re-sync. Please check whether it can be merged to `develop`

**Pull request merged**
